sudo: required
dist: trusty

branches:
  only:
  - master

language: go
go:
  - 1.7.x

env:
- VIPS_VERSION=8.4.5
cache: apt
before_install:
- ./packaging/install-vips.sh

install:
- go get github.com/tools/godep
- godep restore
script:
- make test
