sudo: required
dist: trusty

branches:
  only:
  - master

language: go
go:
  - 1.9.2

env:
- VIPS_VERSION=8.6.0

before_install:
- ./packaging/install-vips.sh

install:
- go get github.com/Masterminds/glide
- go get github.com/wadey/gocovmerge
- glide install

script:
- make ci-trigger

after_success:
- bash <(curl -s https://codecov.io/bash)
