sudo: required
dist: trusty

branches:
  only:
  - master

language: go
go:
  - 1.10.3

env:
  global:
    - VIPS_VERSION=8.6.5
    - secure: dUUIGIfGeWn/Fp4m+0rAj1d2BNr3BZ/qQFDyHJ6z2bskX+Khl8qs5wTqcBiuf+a9DYK2CKjpftiqYNz0TMxeR2zQY7vg+2QgU+r/cSvP1SnURAidmoIzKJyCYoYbMQQZI+/1DihJp/unGu7n6dM716lGqbJFWwbKx1lgKi0eN2a3Mkj5l+cAp1rPLsszpPjX1O9dd5L5ytkwtFC5YV9eUlYTJrg6UPlqmMMJcCGg1clzEB/7V7Ac5ijl0O9Q48xhhzTXsQfs+UGdKEB45WEUgfZ/bjAYHCQzr8MotqGELJTPIXmbUfzcP2RTcp0tfbX5NoKDAl+riaSCZvZkkaE9+z4L4hUG1ZRonQsHtyROzkJd/xM2UFv876XnFCG+fwNy/7SxuP8idWT+PWPvSAbiO1eA942gZXo5KApBD8i21z4hSkVuhHdZLdPwLJwGPG1ngEjbQpMVCh2iuEbnQnEccffnlUIzS7KtxoQ5dfuTfJ63lkBCJgbunylSy0vpE268KJfLaDrCvY0EuXg3H+3/sJ8ty5NXwpW5mZFvwVlnZ1rDw9pea6UwUlkEddWkLpc7rJ/bSyIGrEuN5CVIfgW4ycNq7y4qScraH1Hd6ni+tnjZCPbLct6dLHwHwpXdCqPLAuXN6cKJG/SEWqt6kEe6uw9WMEvYT9zE/VBHdbkcOLY=

before_install:
- ./packaging/install-vips.sh

install:
- go get github.com/Masterminds/glide
- go get github.com/wadey/gocovmerge
- glide install

script:
- make ci-trigger

after_success:
- bash <(curl -s https://codecov.io/bash)
