sudo: required
dist: trusty

branches:
  only:
  - master

language: go
go:
- 1.10.3

env:
  global:
  - VIPS_VERSION=8.6.5
  - secure: iOfz4tQ/0pV+BTnnzzh0cxVHJfw6cgO+O5Gc/48rZIt0LjjIZByvMnatUv2wWlWCM01RhFy0blMAeY7twDSNzqu39voJCZzt4HL1YW8JH9/o4veEMo6MdEpJRQczlJnHpLDRXyW+EcrSunHSE1BQwbEDCBqlISlWBnVuLrvI9en+kQIQjGylazADYkwt0Dljaz73OqEhqqW6obnz7tO4OnTtRZr+lAyQxOCRsEy7Drnc19HWIfORvsAsRnjDboof2WtDoNYYiDEnD89bpiu012OZYI+wik4p2g9fyCLUOpizTI+rLYU0a3M0D6JDmL3fehF+I/s27Hh2uh9QtU8YD2FZ4LthfqkeF1uUyuikMTWI6r1N2EZiKLhFcYezB9R8H+XcsLRwZoxWHHM6OVmkeX7v7LaJYzsNWzPU7YL3Ja1Upn+f9EsK4/mi7uupOLyNUxmOBLa6Anll+IMYor5qmo8S2ahzenREURPuBdZ1OgpheFYK9+9QkkjSCzXm1NjWp1B39a3VtQ1ZVldu7NE7PVRJSWPrfi3YBlcs8qxz54GoAo2yCyPTka12iissVULWQF+fr2NuE2YEPBBZdmi+wHTCZ18V7ts3W8ww7o9ZkAPT9vDKsWVzqe1RmR6Dv+0ocYNVIpyOyL0exHFqujRtbMg4STY6zPaaibcs3bafIq8=

before_install:
- "./packaging/install-vips.sh"

install:
- go get github.com/Masterminds/glide
- go get github.com/wadey/gocovmerge
- glide install

script:
- make ci-trigger

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: BmWHMRbpd3gpOOkn85bRtNzRMCIE4hRO6I/AbhHo/sCv4pay1cXCkWdYMRTkxeLyUg6Ilyx9YVuUFG+tO84el41aaEqhShUGueBTLS8eLALoWcxU6LWE6+VNLFD5kjWd/UllithQ0uPRX1bbcIcmadAMZjhdxCC6pBCdbI7S7YGPby3vbzawPQBAkx17Rmo39/t67zN5gr8KWFltuvlVt6cK6TfC0C4r5jQaqZ49p4NrFJHY1/Rc9+z925zGM0WJ3E9CGH3xRvx5E/0u9l72b2b5iLrMnQzV91G7ZlsVrZqnoAvGgX8Cdw1yJRvC+3RxhCP+dqB3yZFrmDmGuyheNjyf1VOUl9jUnTyY6xAePS+7+Z++gnUv9VzSvW1JFR3iNrc25FsetHIsxaAYnbEsfG5wmSq1jrSHzl7kofaPHbhDvdh4m2xmp19c+8upFyugUnHPwXfIk78/0hqtWbo813MCyaC9Z/FEQPwA0e5lONGBcFemqCRaF9cZRrgBmi/HqB2S/Wcp33lorv4pxKA0frJ930o/RUoCC6kUnSrZQNRwCW2PqdV99E2GpRFJQ9Cq+0VSFX/jB1l8SFOrDIOuXPcPef7JWqCwksoFgIez6o9BO3MREp3QiZicqUS3Bkgsp8tWNdOTtmjDTh16Z6Elz83bvP1ba6gqrzLTDCJY06I=
  on:
    repo: zalando-stups/skrop
