sudo: required
dist: trusty

branches:
  only:
  - master

language: go
go:
  - 1.7.x

env:
- VIPS_VERSION=8.4.5
cache:
  directories:
  - $GOPATH/src
  - $GOPATH/pkg
before_install:
- ./packaging/install-vips.sh

install:
- go get github.com/tools/godep
- go get github.com/wadey/gocovmerge
- godep restore
script:
- ./.travis/test.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
