sudo: false
branches:
  only:
  - master
language: go
go:
  - 1.7.x
addons:
  apt:
    packages:
    - libvips
    - libvips-dev
install:
- go get github.com/tools/godep
- godep restore
script:
- make test
